name: plog
title:
url:
description:

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  care-tips:
    output: true
    path: /:collection/:path/
    title: care-tips


